// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ''//GOOGLE API KEY,
    appId: '1:284088427365:web:a17faceadf38086cffb78c',
    messagingSenderId: '284088427365',
    projectId: 'artified-firebase',
    authDomain: 'artified-firebase.firebaseapp.com',
    databaseURL: 'https://artified-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'artified-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzY0fmIxAfx7PfSKkIra1DLWRiqG0eLM',
    appId: '1:284088427365:android:9e799b211c72fbbdffb78c',
    messagingSenderId: '284088427365',
    projectId: 'artified-firebase',
    databaseURL: 'https://artified-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'artified-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0lL9OKEUK0uqgQ0LKRebi8AGNujm8CY',
    appId: '1:284088427365:ios:6dca426a94cd4cb3ffb78c',
    messagingSenderId: '284088427365',
    projectId: 'artified-firebase',
    databaseURL: 'https://artified-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'artified-firebase.firebasestorage.app',
    iosBundleId: 'com.example.leKatsuAppNew',
  );
}
